# basic options
title: Karthik's Blog
author: Karthik Srinivasan
email: karthiks.625@gmail.com
description: Personal Blog
twitter_username: TheKarthikS
github_username:  karthiklearns

# Build settings
markdown: kramdown
theme: jekyll-athena
